# Generated by Django 4.1.7 on 2023-02-21 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('imagePost', models.CharField(max_length=500, verbose_name='Image')),
                ('contentPost', models.TextField(verbose_name='Content')),
                ('dataPost', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data published')),
            ],
        ),
    ]
